# This file was generated by GoReleaser. DO NOT EDIT.
cask "lsq" do
  name "lsq"
  desc "The ultra-fast CLI companion for Logseq"
  homepage "https://github.com/amiv1/lsq-fork"
  version "2.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lsq"

  on_macos do
    on_intel do
      url "https://github.com/amiv1/lsq-fork/releases/download/v#{version}/lsq_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/amiv1/lsq-fork"
      sha256 "844b273929bbb3370be53999ef54a03471d29180c55b8676c4cabcb17f67c0a6"
    end
    on_arm do
      url "https://github.com/amiv1/lsq-fork/releases/download/v#{version}/lsq_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/amiv1/lsq-fork"
      sha256 "f7147a2554746f1663c84bc450ea7d983ab59cdf4c59c96543bbba3d4ff69e46"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lsq"]
    end
  end

  # No zap stanza required
end
