# This file was generated by GoReleaser. DO NOT EDIT.
cask "lsq" do
  name "lsq"
  desc "The ultra-fast CLI companion for Logseq"
  homepage "https://github.com/amiv1/lsq-fork"
  version "2.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lsq"

  on_macos do
    on_intel do
      url "https://github.com/amiv1/lsq-fork/releases/download/v#{version}/lsq_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/amiv1/lsq-fork"
      sha256 "98962872a64e39f2c027ba3d00862c1dbe498090036a1c81f29d479c3d0f4fb8"
    end
    on_arm do
      url "https://github.com/amiv1/lsq-fork/releases/download/v#{version}/lsq_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/amiv1/lsq-fork"
      sha256 "e63f6eb7a755844af96eff21b5376363ecf3661bb05ab10d3f1c38ba284d4939"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lsq"]
    end
  end

  # No zap stanza required
end
