# This file was generated by GoReleaser. DO NOT EDIT.
cask "lsq" do
  name "lsq"
  desc "The ultra-fast CLI companion for Logseq"
  homepage "https://github.com/amiv1/lsq-fork"
  version "2.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lsq"

  on_macos do
    on_intel do
      url "https://github.com/amiv1/lsq-fork/releases/download/v#{version}/lsq_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/amiv1/lsq-fork"
      sha256 "686883406e3594a845afe3e91421abed24b54f01bcaae6ce36b2dd5b37e1be71"
    end
    on_arm do
      url "https://github.com/amiv1/lsq-fork/releases/download/v#{version}/lsq_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/amiv1/lsq-fork"
      sha256 "e3fe52483226c0652b085fb8b92fb3ac3889cd90043602337ded82bb05a3009b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lsq"]
    end
  end

  # No zap stanza required
end
